### ISSUE TITLE
[CIM] Implement sorting for Subscription Impact Table

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1007]
See https://git.ia.surfsara.nl/netdev/automation/projects/orchestrator-ui/-/issues/36

**Comment by Georgi2704** [comment]
@wouter1975 I'll make this currently work in memory. 

A new ticket for making it work with GraphQL ?

**Comment by Georgi2704** [comment]
GraphQL sorting ticket
https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1233
