### ISSUE TITLE
Fix jest for SURF specific repo

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1008]
See https://git.ia.surfsara.nl/netdev/automation/projects/orchestrator-ui/-/issues/38

**Comment by wouter1975** [comment]
@ricardovdheijden Can be closed?

**Comment by ricardovdheijden** [comment]
Fix was done in SURF specific app and in Example app:
https://github.com/workfloworchestrator/example-orchestrator-ui/pull/41
