### ISSUE TITLE
[bug] Customer contact person names not being loaded 

### ISSUE THREAD

**Issue by Georgi2704** [workfloworchestrator/orchestrator-ui-library#1049]
Contact persons do not load after changing the selected customer:

![Screenshot 2024-04-24 at 16 13 16](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/61829525/48cf68af-79d9-4a32-818b-0ae00d0e7999)
![Screenshot 2024-04-24 at 16 13 04](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/61829525/655af3fe-a48d-4419-902a-00262ec06f2c)

You can reproduce the issue in V2 dev, but also on V1 or V2 locally.

**Comment by DutchBen** [comment]
Backendfix: rename customerKey from 'customer' to 'customer_id': https://github.com/workfloworchestrator/orchestrator-core/pull/715
