### ISSUE TITLE
Form confirm modal buttons

### ISSUE THREAD

**Issue by ricardovdheijden** [workfloworchestrator/orchestrator-ui-library#1052]
The buttons in the confirm modal when leaving a form should be swapped.
![image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/20791917/bdaf1a99-285c-4035-9589-441f8c8d58c4)

The question is asking to leave, so call to action (primary button) should confirm this action

**Comment by dmarjenburgh** [comment]
Regardless of whether the cancel button is left or right, the `confirm` action should be to leave and the `cancel` action to stay.
