### ISSUE TITLE
Configurable OAuth Scopes via Environment Variables

### ISSUE THREAD

**Issue by torkashvand** [workfloworchestrator/orchestrator-ui-library#1055]
**Issue:** 
The authorization scopes for OAuth are currently hardcoded in the NextAuth.js configuration, limiting operational flexibility across different environments.

**Proposed Solution:** 
Implement the ability to set OAuth scopes through environment variables, allowing for easy adjustments without code changes.

**Changes Proposed:**

```javascript
authorization: { params: { scope: process.env.NEXTAUTH_AUTHORIZATION_SCOPE ?? 'openid profile' } },
```

**Comment by torkashvand** [comment]
I am preparing a PR for this.

**Comment by torkashvand** [comment]
These are PRs:

https://github.com/workfloworchestrator/example-orchestrator-ui/pull/26
https://github.com/workfloworchestrator/orchestrator-ui-library/pull/1056

**Comment by wouter1975** [comment]
Both PRs are merged, closing this ticket
