### ISSUE TITLE
Add sorting options to WF/task name in processes table

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1065]
- [ ] Add workflowName to the sortFields from the BE
- [ ] Check filter on substring of the workflowName is not support
  - eg try searchig on `crm`

**Comment by wouter1975** [comment]
waiting for https://github.com/workfloworchestrator/orchestrator-core/issues/648

**Comment by DutchBen** [comment]
It looks like this is already working. @wouter1975 can you have a look if this is still an issue?
