### ISSUE TITLE
Set in sync messages inconsistent

### ISSUE THREAD

**Issue by florisie** [workfloworchestrator/orchestrator-ui-library#1072]
When we set a subscription in sync then we see duplicate messages. One message says completed successful. The other message says failed.

Also the information in the GUI is not updated automatically. We have to reload the page to see the updated info on the subscription details page.

![image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/47642819/be47f2e3-4408-4746-9645-e441c5fdc95e)

Also after clicking the set in sync button we still see this in the GUI:
![image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/47642819/bfff9ed3-6bec-4e49-8786-1cc192cf7f52)

Only after reloading the page I see this:
![image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/47642819/a54a9e3a-4c93-4a75-947c-7c8c2cd3f78e)

**Comment by wouter1975** [comment]
Duplicate toast is already fixed, the second example needs to be checked.

**Comment by wouter1975** [comment]
Is still seen on productieon, need to find a way to reproduce.

**Comment by Georgi2704** [comment]
Let's see how it behaves when is deployed to dev, then we can close it
