### ISSUE TITLE
Toast messages are sometimes shown twice

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1087]
Sometimes the toast is shown twice, in some occassion the toast message is the same sometimes it shows a different message for the second toast.

- [ ] happens when reporting websocket state
- [ ] when setting a subscription in sync

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/fc158f0f-ed22-4bf4-926b-2e44e39f794f)

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/8d68c0a9-7184-467b-a580-fff7cdcbce25)

**Comment by ricardovdheijden** [comment]
Waiting for latest deploy on dev, it might be resolved. Currently unable to reproduce on local devlopment (localhost).

**Comment by wouter1975** [comment]
@ricardovdheijden might be fixed by the latest websocket reconnect fix.

**Comment by ricardovdheijden** [comment]
@wouter1975 , this seem to be fixed
