### ISSUE TITLE
Subscription name needs refresh to be updated in GUI when modified

### ISSUE THREAD

**Issue by Georgi2704** [workfloworchestrator/orchestrator-ui-library#1090]
After running modify_ip_peer and changing the name of the subscription. Clicking on the subscription detail page doesn't show the updated name unless you refresh the page.

![Screenshot 2024-05-08 at 16 46 09](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/61829525/a9a796f4-5913-4ad5-98d1-5e6ddd60a46c)

**Comment by wouter1975** [comment]
Need retesting, after websocket is released.

**Comment by wouter1975** [comment]
Is fixed by websocket.
