### ISSUE TITLE
Chaning firewall speed is not possible

### ISSUE THREAD

**Issue by florisie** [workfloworchestrator/orchestrator-ui-library#1141]
It is currently not possible to change the firewall speed (through the modify FW speed workflow) because the element to select the new product does not show the (correct) options:

![image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/47642819/cf15e7b5-0993-49d0-a31e-cf5831d5013b)

- Shows a product id instead of a list with product names
- It is not a dropdown but just a text field with a pre filled value

**Comment by tjeerddie** [comment]
Woops, forgot to close this, changed in the backend. We had a special input to chose the new product in V1 but changed it to a normal select field for V2.
