### ISSUE TITLE
Remove some SURF specific stuff from orchestrator-core and adapt the GUI afterwards

### ISSUE THREAD

**Issue by acidjunk** [workfloworchestrator/orchestrator-ui-library#122]
Moved from README file to issue:

-   There are fields in the Backend core like: `Process.Assignee` and `Subscription.CustomerAbbrevation` they should be
    removed/changed for enum values like `KLANTSUPPORT`. Probably around 4 a 5 SURF specific fields

**Comment by wouter1975** [comment]
@tjeerddie, can this ticket be closed?
