### ISSUE TITLE
Merge 3 table components into 1 Wfo component

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1326]
Using the new WfoTable component as a basis for Nested table. Verify in chassis-detail/ports tab and in CIM tickets (when that story is implemented)

- [x] Apply the new WfoTable component to the WfoNestedTable component
- [x] Fix the missing key error in console
- [x] Fix the console errors around the nested-table implementations (missing key and DOM error)
- [x] Apply the WfoNestedTable to the tables in the tickets section of the app
- [x] Replace all standard tabels with the new WfoTable component --> todo move this to ticket with table improvements -- https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1384

**Comment by ricardovdheijden** [comment]
Added one more DOD, that is about errors in the console when showing nestedTables
