### ISSUE TITLE
Review example app. Add/review auth documentation.

### ISSUE THREAD

**Issue by DutchBen** [workfloworchestrator/orchestrator-ui-library#1361]
*What*
Write (or rewrite or summarise) documentation that show how to get authorization working and what's involved on both the backend and the frontend

*Why*
Different third parties using WFO have reported issues when getting authorization and authentication working based on the existing documentation. They have gotten it to work eventually but have reported that the documentation is lacking and there is no document that explains both whats needed on the frontend and the backend making it harder to find what's needed and to keep this information aligned. We can draw on previous experience by Rene and ESNet as input for this document

**Comment by DutchBen** [comment]
After consultation with @wouter1975 the scope of this ticket is expanded to include a review of the example-orchestrator. After this ticket the example-orchestrator should
- Work out of the box
- Have all enviroment variables - and no more - listed and documented
- Be able to enable websockets and have websockets work (including with celery worker?) and documented
- Be able to enable authentication and have a working auth example with documentation (back- and frontend)

**Comment by acidjunk** [comment]
I am happy to help: implemented some stuff on backend side for Keycloak / Authenthentication.
Also applying that to a new instance I am running on AWS (with my own keycloak instance).
