### ISSUE TITLE
[NMS] Add notes to `chassis` and `chassis/xxx/port` list page

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1399]
Add `Notes` to the right most column of the following table

![Image](https://github.com/user-attachments/assets/9f8d5ef6-b6ef-4603-bd1f-c9defb3a99c0)

and 
![Image](https://github.com/user-attachments/assets/58c4a5ec-db69-4411-af87-56521c9207f4)

and 

![Image](https://github.com/user-attachments/assets/16430d0d-10e0-4148-a3f2-62f9a4c6253c)

- [ ] As a bonus: remove the expand icon

**Comment by DutchBen** [comment]
For the second screen - Chassis Detail->Port list->Note I need to have it added to the data returned by the federated graphql. I have added a comment for this to https://git.ia.surfsara.nl/netdev/automation/projects/orchestrator/-/issues/2082

**Comment by DutchBen** [comment]
@wouter1975 Are you sure you want the Expand icon removed? I think it's sort of nice to have

**Comment by wouter1975** [comment]
> For the second screen - Chassis Detail->Port list->Note I need to have it added to the data returned by the federated graphql. I have added a comment for this to https://git.ia.surfsara.nl/netdev/automation/projects/orchestrator/-/issues/2082

@DutchBen I thnink the above is relevant to the customer / <customer> / port page, but not for the chassis / <chassis> / port page. Can you add the note column to this page? It is not yet visible in dev.

![Image](https://github.com/user-attachments/assets/fe0dfec5-345a-4cba-8d38-82045d3b40b5)

**Comment by DutchBen** [comment]
> > For the second screen - Chassis Detail->Port list->Note I need to have it added to the data returned by the federated graphql. I have added a comment for this to https://git.ia.surfsara.nl/netdev/automation/projects/orchestrator/-/issues/2082
> 
> [@DutchBen](https://github.com/DutchBen) I thnink the above is relevant to the customer / / port page, but not for the chassis / / port page. Can you add the note column to this page? It is not yet visible in dev.
> 
> ![Image](https://github.com/user-attachments/assets/fe0dfec5-345a-4cba-8d38-82045d3b40b5)

I think it is. There is no note on that level of the port subsription. You could display the note on the chassis subscription but that would be the same for all ports.
