### ISSUE TITLE
[NMS] Fix sorting customer services tab

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1403]
Sort first and second level alphabetically

![Image](https://github.com/user-attachments/assets/c51ef8e8-6aef-4c61-80be-96a5076517bd)

![Image](https://github.com/user-attachments/assets/81745e9e-659a-4a96-a0ca-b30b46077940)

**Comment by wouter1975** [comment]
@DutchBen sorting at the second level is not implemented, would be good to have it sorted on the product tag.

![Image](https://github.com/user-attachments/assets/8f743c78-f0ef-4c0a-b164-ab3d3287f394)

**Comment by DutchBen** [comment]
@wouter1975 Sorting on productTag should be fixed now
