### ISSUE TITLE
Add cache-invalidation to task counter

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#1411]
Counter is not in sync with active tasks.

![Image](https://github.com/user-attachments/assets/bc2cc324-81a5-47ba-bdf4-bb1f1820847d)

Probably use the cache invalidation of the task list

**Comment by Georgi2704** [comment]
The backend should send a websocket message, when the number of status counts changes. 

For example:
`{"name":"invalidateCache","value":{"type":"processStatusCounts"}}
`

**Comment by Georgi2704** [comment]
https://github.com/workfloworchestrator/orchestrator-core/pull/751
