### ISSUE TITLE
Bug: [Websocket] cache invalidation events after callback step?

### ISSUE THREAD

**Issue by DutchBen** [workfloworchestrator/orchestrator-ui-library#1456]
Mahammad@Geant reports that the process detail page doens't update throught the websocket connection when there are callback steps in his form. The websocket connection is established and the backend sends the correct cache invalidation requests, it appears to stop doing that when a callback step is reached.

**Comment by torkashvand** [comment]
I also add this here:

I’ve updated `@orchestrator-ui/orchestrator-ui-components` to version `2.1.0 `and made the necessary code changes. The websocket connection is working well—I can see the green icon, and the Network tab shows `"ping pong"` game between the frontend and backend.
However, after the update, we no longer see asynchronous updates from LSO like before. I debugged both the backend and frontend and noticed after running a workflow websocket sends some events like this:
`{"name":"invalidateCache","value":{"type":"processes","id":"0395d66a-9a10-4634-b88b-a8041badcef3"}}`
and I checked the `orchestrator-ui-components` code and as I understood the invalidateCache  events should do the component re-render for the process detail page but seems doesn’t and we have to refresh the page manually, which is not ideal.
FYI, backend is`![Screenshot 2024-09-23 at 11 35 51](https://github.com/user-attachments/assets/9d48ce0a-b3da-4ceb-924d-894cc67c6560)`
I think this is an issue with frontend code (either in my code or orchestrator-ui-components )
Could you help me figure out what’s causing this issue?
I will also attach a screenshot from ws tab (edited)

**Comment by torkashvand** [comment]
![Screenshot 2024-09-23 at 11 35 51](https://github.com/user-attachments/assets/b429cdff-780e-4cfd-bbc3-fe68b6680f4f)
