### ISSUE TITLE
Change in hooks error when adding translations

### ISSUE THREAD

**Issue by DutchBen** [workfloworchestrator/orchestrator-ui-library#177]
Adding the useTranslation hook to these files triggers a 'detected a change in the order of Hooks called ' error. It seems like it has something to do with the use of useContext. Creating this ticket to keep this out of the scope of the translation ticket

packages/orchestrator-ui-components/src/components/Subscription/ProcessesTimeline.tsx
packages/orchestrator-ui-components/src/components/Subscription/SubscriptionGeneral.tsx

![Image](https://user-images.githubusercontent.com/516374/256815386-989c14fd-e544-4dc5-baa6-9e6eb0f9c136.png)

**Comment by wouter1975** [comment]
@DutchBen is this still relevant?

**Comment by Georgi2704** [comment]
@wouter1975 @DutchBen 
WfoSubscriptionGeneral.tsx:
`    const t = useTranslations('subscriptions.detail');
`
WfoProcessesTimeline.tsx
`    const t = useTranslations('subscriptions.detail.processDetail');
`

Both files are already using translation and don't seem to throw any errors in the console. I think this can be closed.
