### ISSUE TITLE
Add Show/Hide button for side-nav

### ISSUE THREAD

**Issue by ricardovdheijden** [workfloworchestrator/orchestrator-ui-library#210]
Add a show/hide button (icon-only button) in front of the breadcrumb to show/hide the left navigation menu.
Note: the mechanism to trigger this show/hide behavior is already implemented in the logout button at the top right of the screen.

- [ ] Add show/hide icon-only button in front of breadcrumb
- [x] Remove show/hide trigger from logout button

**Comment by wouter1975** [comment]
use this icon type:


![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/deabab7d-adae-43b4-abc2-be412c161816)

**Comment by wouter1975** [comment]
PR #639 with new icon is created. Placement just in front of breadcrumb still to be done.
