### ISSUE TITLE
Review and improve Turborepo project setup

### ISSUE THREAD

**Issue by ricardovdheijden** [workfloworchestrator/orchestrator-ui-library#218]
In the current setup of the repository, requires the developer to have all packages built when working in the local dev environment. This brings some disadvantages:
- The app imports from the dist folder and the IDE links to that dist folder. Causing less optimal developer experience as well as limitations when refactoring code (renaming a type in a lib does not rename the type in the consuming app).
- You have to stop the local dev environment to commit something (this is because of the precommit hooks, running TSC and requires a full build of the project).

The biggest advantage though is that this is very similar, if not, exactly the same as a consumer consuming our library. Making any changes to the project should take this in mind.

Tasks:
- [ ] Config release with github action
- [ ] Prep project to default link to src files and NOT dist folder
- [ ] Nice to have: Add flow to maintain the current dist-folder import to test

**Comment by wouter1975** [comment]
@ricardovdheijden, can be closed?
