### ISSUE TITLE
Project setup: make use of base aliasses

### ISSUE THREAD

**Issue by ricardovdheijden** [workfloworchestrator/orchestrator-ui-library#302]
imports are getting a bit messy due to the many subfolders. Sometimes this results in imports like "../../../component/etc".
Setup some base aliasses like "@components" to have imports like @components/etc

**Comment by acidjunk** [comment]
hmm, we used absolute import for that; which has extra benefits when refactoring components

**Comment by wouter1975** [comment]
closing, most imports have been fixed by now.
