### ISSUE TITLE
Sort icon not visible if column header is ~ same as columnwidth

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#315]
Seen on process list page, the sorting arrow is (partly) lost in the view where the column header roughly the same width as the column itself. 

![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/9f71dcaf-c3ac-43d9-8133-53ab7545c0dd)

Solution directions?
* Either add a minimal width
* Or crop the header text such that the sorting arrow can always be shown
- [ ] solution proposed by Ruben, is to overlay the sorting arrow on top of the column header

**Comment by Georgi2704** [comment]
@wouter1975 I believe this has been already fixed:
![Image](https://github.com/user-attachments/assets/29dd70f2-692d-4359-af7c-43a9c2b7fe6b)
