### ISSUE TITLE
Add missing form input field from V1 code

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#337]
Add the missing form input fields including the SURF specific components, so that all SURF workflows can be run.

Missing inputs:
- [ ] prefix
- [ ] Portselect
- [x] NodeSelect (@DutchBen)
- [x] Selectfield (@DutchBen)
- [x] ContactPersons

Please complement the list above.

The list of fields not implemented from V1 an their names are:

- [ ] AcceptField (@ricardovdheijden)
- [x] DateField, (@DutchBen)
- [x] ListField, (@ricardovdheijden) -- Also: **ListAddField, ListItemField, ListDelField**
- [x] LocationCodeField, (needs an ApplicationContext) (@DutchBen, part of select)
- [x] NestField, (@ricardovdheijden )
- [x] OptGroupField, (@ricardovdheijden)
- [x] OrganisationField, (in v1 exists in a SURF and Non SURF context) @DutchBen 
- [x] RadioField, (@ricardovdheijden )
- [ ] SubscriptionField,
- [x] SubscriptionSummaryField,
- [x] SummaryField,  << Claimed by Ruben
- [ ] Translations: V1 uses backend driven translations

Surf only:
- [x] TimestampField (@Dutchben)
- [x] ContactPersonNameField, (in v1 exists in a SURF and Non SURF context) @DutchBen 
- [ ] ImsPortIdField 
- [ ] IPvAnyNetworkField
- [x] ImsNodeIdField (@DutchBen, part of select)
- [x] VlanField (@DutchBen)

Keep React select as part of the code, include unit tests from V1, and check if it still works

**Comment by acidjunk** [comment]
Complemented the inputs (only SURF specific)

**Comment by ricardovdheijden** [comment]
Mocking form data:

packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx
insert before `const prefilledForm...`
```
const stepUserInputWithTestFields: JSONSchema6 = {
        ...stepUserInput,
        properties: {
            ...stepUserInput.properties,
            test_select: {
                title: 'Test Select',
                allowedValues: ['value 1', 'value 2', 'value 3'],
                checkboxes: false,
            },
            test_radio: {
                title: 'Test Radio',
                allowedValues: ['value 1', 'value 2', 'value 3'],
                checkboxes: true,
            },
        },
    };

    //const prefilledForm = fillPreselection(stepUserInput, location.search);
    const prefilledForm = fillPreselection(stepUserInputWithTestFields, router);
```

**Comment by wouter1975** [comment]
@DutchBen can this one be closed?
