### ISSUE TITLE
Optimise subscription configuration tree navigation

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#346]
Consider the following design, idea is to support tree expansion more easily and finegrained.

- [x] the standard expand and collapse icons before the tree node should expand or collapse the complete branch until the `end` leaves
- [x] remove the expand/collapse tree all icon  next to the product block header

![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/7b8f2f4b-eb4d-4304-a620-ee9f21830963)

**Comment by acidjunk** [comment]
fixed in #377
