### ISSUE TITLE
JSX props and arrow functions + other code styles

### ISSUE THREAD

**Issue by acidjunk** [workfloworchestrator/orchestrator-ui-library#363]
We have a lot of toggles that use current state and assume state changes are always sequential:

<img width="770" alt="Screenshot 2023-10-12 at 20 14 41" src="https://github.com/workfloworchestrator/orchestrator-ui/assets/685002/750ea395-04ad-4a41-93c6-7a70fe05bbb9">

We als have a lot of JSX props that contain arrow functions:
https://stackoverflow.com/questions/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind

Probably more quircks; so I openend this ticket, based on discussions in #277 to keep track of them

**Comment by wouter1975** [comment]
Closing this ticket, as the example of the sidenav is currently not causing issues.
