### ISSUE TITLE
Table: remove bottom bar on tables with 1 page

### ISSUE THREAD

**Issue by ricardovdheijden** [workfloworchestrator/orchestrator-ui-library#397]
In the case when showing small data sets in the table only covering one page, the page controls for the table should be hidden as they have no effect / are not usefull.

- [ ] If data fits on 1 page , do not show the page controls
- [ ] When just a filter is applied the page controls should still be visible (to be discussed)

To discuss:
We need to go through the corner cases for this story, for example:
What to do when we have 70 results on a pagesize of 100 AND we would like to change the pagesize to 25 for example

**Comment by wouter1975** [comment]
probably not preferred if the download button is added below the table. see #544

**Comment by wouter1975** [comment]
won't fix
