### ISSUE TITLE
Businessrules not correctly validated using user input in workflows

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#546]

**Comment by florisie** [comment]
In the system-tests I use a relatively low screen size. What I noticed in the workflows table is that the column with the actual link to the workflow is one of the first to dissappear. I think it should be the last one to dissappear:
![image](https://github.com/workfloworchestrator/orchestrator-ui/assets/47642819/da27a5ae-54a4-47f3-b30b-660f49092c2b)
