### ISSUE TITLE
Add option to clear/reset the TSV index

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#547]
The TSV column is critical in the filter options of the subscription table. It the TSV is not being updated anymore, or corrupt, it will be very useful for the user to quickly reset this column, like a cache clear.

- [ ] ~~add a option in the clear cache dropdown~~
- [ ] or, add a new action button to trigger this TSV reset.
  - To reset the search-index, make a POST to: api/settings/search-index/reset
  - On success, it will return a status 200 response (no payload).
- [ ] ~~add a new dropdown item in de clear cache settings~~ --> probably not the best place as the values in the dropdown are driven by the backend.
  - ~~Text in dropdown "Clear all text search indexes from subscriptions table"~~

- [ ] ~~add this function to the subscription page with the button text: `Reset search index`~~
  -  ~~at the same place as the Retry buttons on the task page.~~

**Comment by wouter1975** [comment]
see https://github.com/workfloworchestrator/orchestrator-core/issues/432

**Comment by dmarjenburgh** [comment]
To reset the search-index, make a POST to: `api/settings/search-index/reset`
On success, it will return a status 200 response (no payload).

I suggest to make the dropdown text into `Reset text search indexes`, as people will not (or shouldn't have to) know what a TSV column is.
