### ISSUE TITLE
Align icons to design style

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#576]
Replace the following icons with project specific icons, using the icons found on https://heroicons.com/.

```
<EuiIcon type="devToolsApp" /> --> use solid cube
<EuiIcon type="submodule" /> --> use solid cog-6-tooth --> use the only from existing icons in repo
<EuiIcon type="indexRuntime" /> --> use solid play-circle
<EuiIcon type="heatmap" />  --> use solid share
```

![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/e36f7b92-5035-465a-8e0d-d96bd36ade30)

see https://github.com/workfloworchestrator/orchestrator-ui/pull/595
- [x] add icons
- [x] update subscription tab with new icons
- [x] color icons blue is tab is selected on subscription detail page
  - [x] see WfoBell ticket

**Comment by wouter1975** [comment]
@Georgi2704 , can you fix this issue, as you have done this already in CIM?

**Comment by Georgi2704** [comment]
Closed by https://github.com/workfloworchestrator/orchestrator-ui-library/pull/696
