### ISSUE TITLE
This dialog is only true for the first page

### ISSUE THREAD

**Issue by acidjunk** [workfloworchestrator/orchestrator-ui-library#602]
<img width="1205" alt="Screenshot 2023-12-20 at 14 48 26" src="https://github.com/workfloworchestrator/orchestrator-ui/assets/685002/9d5319d9-38e3-4005-b27a-71ee0806ec08">

When you navigate back from the second page of a wizard.

**Comment by wouter1975** [comment]
@acidjunk, I think this modal is actually correct, as filled in data will indeed be lost.
