### ISSUE TITLE
Replace hardcoded styles values with values from the theme and implement dark theme design

### ISSUE THREAD

**Issue by Georgi2704** [workfloworchestrator/orchestrator-ui-library#626]
Currently some stylesheets are applying hardcoded values instead of using the orchestrator theme. Such are the styles of WfoWorkflowSteps.

`    const stepStateSuccessIconStyle = css({
        ...stepStateIcon,
        backgroundColor: '#CCE3F4',
    });`
    
A solution could be to use `toSecondaryColor` with `theme.colors.primary`

- [ ] implement the new dark theme style, and check all badges are changed correctly from LIGHT to DARK.
- [ ] fix colour of button after visit, which makes the dark/light theme button slightly lighter
![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/b92f40b0-8ef7-4ca3-8fd6-43cea7a4923a)
- [ ] use the new proposed colour scheme of Vishal
- [ ] Verify if toHexColorWithOpacity helper is still needed

```
        DARK: {
            primary: '#0077C8',
            accent: '#E67300',
            success: '#13B054',
            warning: '#FFC514',
            danger: '#FF4F46',
            primaryText: '#1F8DD8',
            accentText: '#E67300',
            successText: '#13B054',
            warningText: '#FFC514',
            dangerText: '#FF4F46',
            emptyShade: '#ffffff',
            lightestShade: '#F1F5F9',
            lightShade: '#9CA3AF',
            mediumShade: '#4B5563',
            darkShade: '#374151',
            darkestShade: '#1F2937',
            fullShade: '#101827',
            text: '#9CA3AF',
            title: '#ffffff',
            subduedText: '#9CA3AF',
            link: '#1F8DD8',
            body: '#9CA3AF',
            highlight: '#51482F',
            disabled: '#4B5563',
            disabledText: '#4B5563',
            shadow: '#000000',
        },
```

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/019d9ebd-8d0b-472a-96f9-2bc8a6f95f4f)

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/54d88e4b-e3ec-47a8-b7c3-6bf22abd90eb)

**Comment by wouter1975** [comment]
First merge the Dask theme PR

**Comment by ricardovdheijden** [comment]
The current mechanism to switch between the themes does not work:
- in the example app both dark and light css files are imported, but only 1 applies all the time (light theme).
- The dark theme css is MISSING in the surf specific app
- Already "done" work in scope of this store were corrections on the light theme. This is wrong and might need to be partially rolled back.
- Highest priority would be to make the toggle properly work. A good indication of a "working" css file would be that the textfields of the http://localhost:3001/forms page actually would turn dark of light (using the current main branch as a basis)
