### ISSUE TITLE
Add NPM and Github documentation

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#659]
- [x] extend Readme with detail on storybook, changesets, release to NPM
- [x] add information in NPM with link to github and some project information
- [x] some information added to github orchestrator-ui-library
- [x] add information how to work with the new project setup
- [x] investigate if changesets can be inserted in the version history of NPM
https://www.npmjs.com/package/@orchestrator-ui/orchestrator-ui-components?activeTab=versions

**Comment by DutchBen** [comment]
Changesets can't be added to the releases tab on npm directly. I have added a CHANGE log file that refers to the correct locations.
