### ISSUE TITLE
PB title is not fully shown - use new truncate function of EUI

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#699]
- [x] PB title is not fully shown - use new truncate function of EUI
  - see https://orchestrator-v2.dev.automation.surf.net/subscriptions/9de74c3f-015c-4ff2-8d9e-9a9db459f398
- [x] Ensure that mouse-over will show the full text when hoovering over the tree

**Comment by Georgi2704** [comment]
It seems that the new truncate function **<EuiTextTruncate>** is not supported by **<EuiListGroupItem>**, so a custom component should be built instead of using the current EuiListGroupItem.
