### ISSUE TITLE
[Medium] L2VPN - ESI component is loosing selected ports when adding ports

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#729]
While adding a port to the ESI, the selected ports will be lost temporarily. After some time the previous selected ports are shown again.

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/66990cc5-67c0-499e-8283-73ba85297f92)

**Comment by tjeerddie** [comment]
tested it and I can't reproduce it anymore after PR: https://github.com/workfloworchestrator/orchestrator-ui-library/pull/754
