### ISSUE TITLE
Error when trying to edit existing peer

### ISSUE THREAD

**Issue by florisie** [workfloworchestrator/orchestrator-ui-library#740]
In an IP Peer modify workflow, when I select to edit an existing peering then the following page of the form will not render correctly:
![image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/47642819/51c8588f-4da5-4376-8c7e-cc008cd843db)
![image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/47642819/c430dee8-ab4b-4f69-89aa-57f5d2597ece)

**Comment by wouter1975** [comment]
Is fixed, all seems to work as expected. @florisie
