### ISSUE TITLE
Add `in-use by` component to render in-use by subscriptions on detail subscription page

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#776]
Below is a bug reported, which is actually not yet implemented. Therefore this ticket is changed into a feature ticket

In V1 the view of in-use by subscriptions is:

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/8911a017-0df1-4cc8-8056-7bf1c88262a0)

Use the same approach as in V1 to show the subscription with the following details and when complying to the following condition:
* No terminated subscriptions are listed
* Make subscription unique
* Show `subscription description`
* Show 'product type`
* Show Subscription ID in short 8-ch uuid, with link to subscription detail page in new tab 
* add `copy` option for subscription_id on hoover

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/ea71507f-863b-493a-9e0f-e0b9264974f8)

---
---
---

## Reported bug `AGGSP still in use while in-use-by subscription has been terminated`

When I look at the details of an AGGSP then I see that it is still "in-use-by" while the "in-use-by" subscription has been terminated.

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/732933fc-d079-45f0-944f-5cf116f93f54)

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/80160ae9-4227-4d7c-be55-6614cab54012)

**Comment by tjeerddie** [comment]
V1 also shows terminated subscriptions and has logic to show more data and remove duplicates. we would need to implement functionality for it in V2
