### ISSUE TITLE
[bug] L3VPN shows wrong VLAN validator message

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#780]
V2:
![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/509d3084-03ef-48c0-8573-ec218350b422)

V1:

![Image](https://github.com/workfloworchestrator/orchestrator-ui-library/assets/83226590/4522b75c-8dd9-4400-8f5a-d5e18a638d5e)

**Comment by DutchBen** [comment]
@wouter1975 The message shown is different from V1 but isn't the real fix to not show a message at all until a post is selected?

**Comment by wouter1975** [comment]
@DutchBen , that sounds like a good solution indeed. I recall that we might need to show the message on the vlan field in case of untagged ports or ports  used in a core_link, can we keep this, whie we hide it in the situation of a L3VPN?
