### ISSUE TITLE
[CIM] Show toast for service tickets for non-closed tickets with startdate in past-24h exist

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#797]
see https://git.ia.surfsara.nl/netdev/automation/projects/orchestrator-ui/-/issues/21

**Comment by Georgi2704** [comment]
https://eui.elastic.co/#/display/callout

@wouter1975 
Could this be better than a toast ?
We can place it above the service ticket list table.

**Comment by wouter1975** [comment]
Yes, I like it. Maybe just try this if you can manage this in ~2 hours work?
