### ISSUE TITLE
Change websocket logic

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-ui-library#823]
after backend ticket https://github.com/workfloworchestrator/orchestrator-core/issues/502 is delivered, consider these things in the frontend:
- objects are send to allow for multiple websocket functionality, backend will send `{ "invalidateCache": "Cache key" }` for cache invalidation.
- debounce or throttle to stop spam of http requests with fast workflows.
- add authentication.
- make processes list page work with the cache invalidation.

**Comment by wouter1975** [comment]
is being implemented as we speak
