### ISSUE TITLE
Websocket interface update

### ISSUE THREAD

**Issue by DutchBen** [workfloworchestrator/orchestrator-ui-library#941]
Based on work from this backend PR: https://github.com/workfloworchestrator/orchestrator-core/pull/564 the interface for messages coming from and going to the websocket endpoint /api/ws/events has changed slightly. This ticket is for aligning backend and frontend again

extra: Make websocket toggle disable polling on processpage

- [ ] First implement the manual reconnect ws
- [ ] replace Websocket idcon (highlight broken websocket icon) with tooltip

**Comment by wouter1975** [comment]
Ws is broken now on dev, probably due to oauth = true
